

class StartError(Exception):
    pass


class LimitError(Exception):
    pass